#!/bin/bash -e
# postrm script for vtrunkd
#
# see: dh_installdeb(1)

set -e

case ${1} in

    remove|upgrade|deconfigure)
	
	service vtrunkd-helper stop || true
	
    ;;

    failed-upgrade)

    ;;

    *)

        echo "prerm no reconoce el argumento '"${1}"'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0